<a href="https://colab.research.google.com/github/zi-onion/ESAA/blob/main/03_08_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
array1 = np.zeros(10)
array1

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
memorysize = array1.nbytes
memorysize

80

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array1[4]=1
array1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array2 = np.arange(10,50)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.sort(array2)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array3 = np.arange(0,9)
array3

array3.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array4 = np.array([1,2,0,0,4,0])

nonzero = np.nonzero(array4)
nonzero

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random1 = np.random.rand(3,3,3)
random1

array([[[0.54112818, 0.24443461, 0.91832562],
        [0.7588154 , 0.72817766, 0.55185756],
        [0.49828624, 0.83272136, 0.42298714]],

       [[0.17991962, 0.59212244, 0.02239284],
        [0.33535666, 0.69657644, 0.53665609],
        [0.32153155, 0.05734518, 0.57760129]],

       [[0.12354286, 0.70717962, 0.84361635],
        [0.161898  , 0.05868573, 0.42581795],
        [0.97548924, 0.86060036, 0.14437652]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random2 = np.random.rand(10,10)

min = np.min(random2)
max = np.max(random2)

print(min,max)

0.007527358389586292 0.999495504422044


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random3 = np.random.rand(30)
np.mean(random3)

0.46403930285627953

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array2d = np.ones((5, 7))
array2d[1:-1, 1:-1] = 0

print(array2d)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix = np.diag([1, 2, 3, 4],k=-1)
matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

checkerboard

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
indices = np.unravel_index(99, (6, 7, 8))
indices

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
random = np.random.rand(5, 5)

normalize = (random - np.mean(random)) / (np.std(random))
normalize

array([[-0.84009163, -0.9769743 , -0.40254987, -0.80286545, -0.48857277],
       [-1.27026231,  0.50557044, -0.21043346,  1.85935783, -0.68840754],
       [-0.90069581, -0.04976255,  1.84771717,  1.7165636 , -0.07100226],
       [ 0.13821247, -0.55766544,  1.69631709,  0.47181664,  1.30386656],
       [-0.21421252,  0.93043122, -0.61515239, -1.27750582, -1.10369889]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))

9


In [ ]:
from numpy import *

In [ ]:
print(sum(range(5),-1))

10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

위에 5개는 올바르며, 마지막만 올바르지 않음

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

<ipython-input-67-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) // np.array(0)

<ipython-input-68-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-69-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

np.intersect1d(Z1, Z2)

array([4, 5, 7, 8, 9])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-5-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange(np.datetime64(start_date), np.datetime64(end_date) + np.timedelta64(1, 'D'), dtype='datetime64[D]')


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

v1=np.add(A, B)
v2=np.divide(np.negative(A),2)
np.multiply(v1,v2)

array([ -2.5,  -7. , -13.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
random_array = np.random.rand(5) * 10

method1 = random_array % 1
method2 = random_array // 1

print(method1)
print(method2)


[0.85109186 0.61551945 0.42843175 0.07564376 0.38096388]
[7. 2. 0. 5. 0.]




```
# This is formatted as code
```

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.zeros((5, 5)) + np.arange(5)

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


```
# This is formatted as code
```

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)

print("Original Vector:", random_vector)
print("Sorted Vector:", sorted_vector)

Original Vector: [0.76990379 0.24951545 0.16431849 0.60624228 0.15894803 0.95651436
 0.08230302 0.85463734 0.18624421 0.42760159]
Sorted Vector: [0.08230302 0.15894803 0.16431849 0.18624421 0.24951545 0.42760159
 0.60624228 0.76990379 0.85463734 0.95651436]


**bold text**#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
cartesian_coordinates = np.random.rand(10, 2)

x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)

print(cartesian_coordinates)
np.column_stack((radius, angle))

[[0.98092464 0.09492167]
 [0.83149772 0.40527969]
 [0.09554556 0.47576052]
 [0.17389335 0.43484151]
 [0.55543702 0.00461328]
 [0.56021353 0.0957527 ]
 [0.80353427 0.4049428 ]
 [0.93090962 0.41437395]
 [0.87614224 0.95745768]
 [0.41273606 0.89063583]]


array([[0.98550661, 0.09646719],
       [0.92500816, 0.45352438],
       [0.48525975, 1.37260569],
       [0.46832258, 1.1903757 ],
       [0.55545617, 0.00830549],
       [0.56833773, 0.16928592],
       [0.89980331, 0.46680431],
       [1.01896933, 0.418795  ],
       [1.29782527, 0.82971656],
       [0.98162275, 1.13684075]])

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.random.rand(10)

max_index = Z.argmax()

Z[max_index] = 0

print(Z)
print(max_index)

[0.4047314  0.23237709 0.78470539 0.51986597 0.45985933 0.
 0.41445901 0.72369861 0.06684242 0.21519169]
5


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)

v = np.random.uniform(0, 100)

distances = np.abs(Z - v)
closest_index = np.argmin(distances)

Z[closest_index]

3

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
for index in np.ndindex(Z.shape):
    value = Z[index]
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 'size of a 2D array'
p = 'the number of elements that you want to place'

Z = np.zeros((n,n))

indices = np.random.choice(range(n * n), p, replace=False)
value_to_place = 42

np.put(Z, indices, value_to_place)

print(Z)

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
Z = np.random.randint(0, 10, (3, 3))
print(Z)

[[2 9 7]
 [1 1 4]
 [1 0 9]]


In [ ]:
sorted_by_column1 = Z[Z[:, 0].argsort()]
sorted_by_column1

array([[1, 1, 4],
       [1, 0, 9],
       [2, 9, 7]])

In [ ]:
# column 2
sorted_by_column2 = Z[Z[:, 1].argsort()]
sorted_by_column2

array([[1, 0, 9],
       [1, 1, 4],
       [2, 9, 7]])

In [ ]:
# column 3
sorted_by_column3 = Z[Z[:, 2].argsort()]
sorted_by_column3

array([[1, 1, 4],
       [2, 9, 7],
       [1, 0, 9]])